import { createContext, useContext, useState } from "react";

export const LANGUAGES = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "hi", label: "हिंदी", flag: "🇮🇳" },
  { code: "mr", label: "मराठी", flag: "🟠" },
  { code: "bn", label: "বাংলা", flag: "🟦" },
  { code: "ta", label: "தமிழ்", flag: "🟩" },
  { code: "te", label: "తెలుగు", flag: "🟨" },
  { code: "gu", label: "ગુજરાતી", flag: "🟪" },
  { code: "kn", label: "ಕನ್ನಡ", flag: "🔴" },
];

// All UI strings in all languages
export const T = {
  en: {
    appName: "YojnaPortal",
    tagline: "GOVERNMENT SCHEME FINDER",
    nav_home: "🏠 Home", nav_schemes: "📋 Schemes", nav_checker: "✅ Eligibility",
    login_btn: "Login / Sign Up", logout: "Logout",
    hero_title1: "Find Your Scheme,", hero_title2: "Claim Your Right",
    hero_sub: "500+ government schemes in one place. Check eligibility, know documents, and apply directly.",
    search_placeholder: "Search schemes... (e.g. scholarship, farming, health)",
    search_btn: "Search", quick_actions: "Quick Actions",
    check_elig: "Check Eligibility", check_elig_desc: "Find schemes based on your profile",
    edu_schemes: "Education Schemes", edu_desc: "Scholarships & academic support",
    farm_schemes: "Farmer Schemes", farm_desc: "Agriculture schemes & subsidies",
    health_schemes: "Health Schemes", health_desc: "Medical support & insurance",
    explore: "Explore →",
    all_schemes: "All Government Schemes",
    all_schemes_sub: "Browse and filter from our complete database of central government schemes.",
    schemes_found: "schemes found",
    ministry: "Ministry",
    benefit: "BENEFIT", deadline_lbl: "DEADLINE",
    req_docs: "📄 Required Documents",
    eligibility_lbl: "✅ Eligibility",
    apply_btn: "🚀 Apply on Official Website",
    all_genders: "All Genders", female_only: "Female Only", male_only: "Male",
    age_lbl: "Age", income_lbl: "Income",
    checker_title: "Eligibility Checker",
    checker_sub: "Fill your details — we'll find the best schemes for you.",
    login_required: "Login Required",
    login_required_sub: "Please login to use the Eligibility Checker. Create a free account in one minute!",
    login_to_continue: "🔑 Login / Sign Up",
    step1: "Personal Info", step2: "Education & Work", step3: "Income & Category", step4: "Your Schemes",
    age_field: "Your Age *", gender_field: "Gender *", state_field: "State / UT",
    next_btn: "Next →", back_btn: "← Back",
    occupation_field: "Current Occupation *", education_field: "Highest Education",
    other_occupation_placeholder: "Please describe your occupation...",
    income_field: "Annual Family Income (₹)",
    income_hint: "Annual family income",
    category_field: "Social Category",
    find_btn: "🎯 Find My Schemes",
    results_found: "Schemes Found!", no_results: "No schemes matched",
    results_sub: "Eligibility checked based on your profile.",
    ai_label: "🤖 AI RECOMMENDATION",
    view_detail: "View →",
    recheck: "↺ Check Again",
    no_scheme_msg: "No schemes found for your criteria. Try changing the filters.",
    welcome: "Welcome",
    member_since: "Member since",
    stats_schemes: "Schemes Listed", stats_cat: "Categories", stats_citizens: "Citizens Helped", stats_avail: "Available",
    select_gender: "Select gender", male: "Male", female: "Female", other_gender: "Other",
    select_state: "Select state",
    select_occ: "Select occupation", student: "Student", farmer: "Farmer / Kisan",
    self_emp: "Self-Employed / Business", govt_emp: "Government Employee",
    pvt_emp: "Private Employee", unemployed: "Unemployed", other_occ: "Other (Please specify)",
    select_edu: "Select education", below_10th: "Below 10th / School going",
    none_baby: "Not Applicable (Baby/Infant)", edu_10th: "10th Pass", edu_12th: "12th Pass",
    graduation: "Graduation", post_grad: "Post Graduation", diploma: "Diploma / ITI",
    select_cat: "Select category", general: "General", obc: "OBC", sc: "SC", st: "ST",
    minority: "Minority", ews: "EWS",
    income_exceeded: "⚠️ Based on your income, you may not be eligible for income-restricted schemes. Showing all applicable schemes.",
    footer_copy: "YojnaPortal — Powered by Government of India Open Data",
    footer_sub: "Made with ❤️ for Indian Citizens · Not an official government website",
    language_label: "🌐 Language",
    pm_section: "Message from PM",
    view_details: "View Details",
  },
  hi: {
    appName: "योजना पोर्टल",
    tagline: "सरकारी योजना खोजक",
    nav_home: "🏠 होम", nav_schemes: "📋 योजनाएं", nav_checker: "✅ पात्रता",
    login_btn: "लॉगिन / साइन अप", logout: "लॉगआउट",
    hero_title1: "अपनी योजना खोजें,", hero_title2: "अपना हक पाएं",
    hero_sub: "500+ सरकारी योजनाएं एक जगह। पात्रता जांचें, दस्तावेज जानें और सीधे आवेदन करें।",
    search_placeholder: "योजना खोजें... (जैसे छात्रवृत्ति, किसान, स्वास्थ्य)",
    search_btn: "खोजें", quick_actions: "त्वरित क्रियाएं",
    check_elig: "पात्रता जांचें", check_elig_desc: "अपने प्रोफाइल के आधार पर योजनाएं खोजें",
    edu_schemes: "शिक्षा योजनाएं", edu_desc: "छात्रवृत्ति और शैक्षणिक सहायता",
    farm_schemes: "किसान योजनाएं", farm_desc: "कृषि योजनाएं और सब्सिडी",
    health_schemes: "स्वास्थ्य योजनाएं", health_desc: "चिकित्सा सहायता और बीमा",
    explore: "देखें →",
    all_schemes: "सभी सरकारी योजनाएं",
    all_schemes_sub: "केंद्र सरकार की सभी योजनाओं का डेटाबेस।",
    schemes_found: "योजनाएं मिलीं",
    ministry: "मंत्रालय",
    benefit: "लाभ राशि", deadline_lbl: "अंतिम तिथि",
    req_docs: "📄 आवश्यक दस्तावेज",
    eligibility_lbl: "✅ पात्रता",
    apply_btn: "🚀 आधिकारिक वेबसाइट पर आवेदन करें",
    all_genders: "सभी लिंग", female_only: "केवल महिला", male_only: "पुरुष",
    age_lbl: "आयु", income_lbl: "आय",
    checker_title: "पात्रता जांचकर्ता",
    checker_sub: "अपनी जानकारी भरें — हम आपके लिए सबसे अच्छी योजनाएं खोजेंगे।",
    login_required: "लॉगिन आवश्यक है",
    login_required_sub: "पात्रता जांचकर्ता का उपयोग करने के लिए पहले लॉगिन करें।",
    login_to_continue: "🔑 लॉगिन / साइन अप",
    step1: "व्यक्तिगत जानकारी", step2: "शिक्षा और काम", step3: "आय और श्रेणी", step4: "आपकी योजनाएं",
    age_field: "आपकी आयु *", gender_field: "लिंग *", state_field: "राज्य / केंद्र शासित प्रदेश",
    next_btn: "आगे →", back_btn: "← वापस",
    occupation_field: "वर्तमान व्यवसाय *", education_field: "उच्चतम शिक्षा",
    other_occupation_placeholder: "कृपया अपना व्यवसाय बताएं...",
    income_field: "वार्षिक पारिवारिक आय (₹)",
    income_hint: "वार्षिक पारिवारिक आय",
    category_field: "सामाजिक श्रेणी",
    find_btn: "🎯 योजनाएं खोजें",
    results_found: "योजनाएं मिलीं!", no_results: "कोई योजना नहीं मिली",
    results_sub: "आपके प्रोफाइल के आधार पर पात्रता जांची गई।",
    ai_label: "🤖 AI सुझाव",
    view_detail: "देखें →",
    recheck: "↺ दोबारा जांचें",
    no_scheme_msg: "आपकी जानकारी के अनुसार कोई योजना नहीं मिली।",
    welcome: "स्वागत",
    member_since: "सदस्य बने",
    stats_schemes: "योजनाएं सूचीबद्ध", stats_cat: "श्रेणियां", stats_citizens: "नागरिक लाभान्वित", stats_avail: "उपलब्ध",
    select_gender: "लिंग चुनें", male: "पुरुष", female: "महिला", other_gender: "अन्य",
    select_state: "राज्य चुनें",
    select_occ: "व्यवसाय चुनें", student: "छात्र", farmer: "किसान",
    self_emp: "स्व-रोजगार / व्यवसाय", govt_emp: "सरकारी कर्मचारी",
    pvt_emp: "निजी कर्मचारी", unemployed: "बेरोजगार", other_occ: "अन्य (कृपया बताएं)",
    select_edu: "शिक्षा चुनें", below_10th: "10वीं से कम / स्कूल जा रहे हैं",
    none_baby: "लागू नहीं (शिशु/बच्चा)", edu_10th: "10वीं पास", edu_12th: "12वीं पास",
    graduation: "स्नातक", post_grad: "स्नातकोत्तर", diploma: "डिप्लोमा / आईटीआई",
    select_cat: "श्रेणी चुनें", general: "सामान्य", obc: "OBC", sc: "SC", st: "ST",
    minority: "अल्पसंख्यक", ews: "EWS",
    income_exceeded: "⚠️ आपकी आय के आधार पर आप कुछ योजनाओं के लिए पात्र नहीं हो सकते।",
    footer_copy: "योजना पोर्टल — भारत सरकार के ओपन डेटा पर आधारित",
    footer_sub: "भारतीय नागरिकों के लिए ❤️ के साथ बनाया गया · यह आधिकारिक सरकारी वेबसाइट नहीं है",
    language_label: "🌐 भाषा",
    pm_section: "प्रधानमंत्री का संदेश",
    view_details: "विवरण देखें",
  },
  mr: {
    appName: "योजना पोर्टल",
    tagline: "शासकीय योजना शोधक",
    nav_home: "🏠 मुखपृष्ठ", nav_schemes: "📋 योजना", nav_checker: "✅ पात्रता",
    login_btn: "लॉगिन / साइन अप", logout: "लॉगआउट",
    hero_title1: "तुमची योजना शोधा,", hero_title2: "तुमचा हक मिळवा",
    hero_sub: "500+ शासकीय योजना एका ठिकाणी. पात्रता तपासा, कागदपत्रे जाणा आणि थेट अर्ज करा.",
    search_placeholder: "योजना शोधा... (उदा. शिष्यवृत्ती, शेतकरी, आरोग्य)",
    search_btn: "शोधा", quick_actions: "त्वरित क्रिया",
    check_elig: "पात्रता तपासा", check_elig_desc: "तुमच्या प्रोफाइलनुसार योजना शोधा",
    edu_schemes: "शिक्षण योजना", edu_desc: "शिष्यवृत्ती आणि शैक्षणिक मदत",
    farm_schemes: "शेतकरी योजना", farm_desc: "कृषी योजना आणि अनुदान",
    health_schemes: "आरोग्य योजना", health_desc: "वैद्यकीय मदत आणि विमा",
    explore: "पाहा →",
    all_schemes: "सर्व शासकीय योजना",
    all_schemes_sub: "केंद्र सरकारच्या सर्व योजनांचा डेटाबेस.",
    schemes_found: "योजना सापडल्या",
    ministry: "मंत्रालय",
    benefit: "लाभ रक्कम", deadline_lbl: "अंतिम तारीख",
    req_docs: "📄 आवश्यक कागदपत्रे",
    eligibility_lbl: "✅ पात्रता",
    apply_btn: "🚀 अधिकृत वेबसाइटवर अर्ज करा",
    all_genders: "सर्व लिंग", female_only: "केवळ महिला", male_only: "पुरुष",
    age_lbl: "वय", income_lbl: "उत्पन्न",
    checker_title: "पात्रता तपासक",
    checker_sub: "तुमची माहिती भरा — आम्ही तुमच्यासाठी सर्वोत्तम योजना शोधू.",
    login_required: "लॉगिन आवश्यक",
    login_required_sub: "पात्रता तपासक वापरण्यासाठी प्रथम लॉगिन करा.",
    login_to_continue: "🔑 लॉगिन / साइन अप",
    step1: "वैयक्तिक माहिती", step2: "शिक्षण आणि काम", step3: "उत्पन्न आणि श्रेणी", step4: "तुमच्या योजना",
    age_field: "तुमचे वय *", gender_field: "लिंग *", state_field: "राज्य / केंद्रशासित प्रदेश",
    next_btn: "पुढे →", back_btn: "← मागे",
    occupation_field: "सध्याचा व्यवसाय *", education_field: "सर्वोच्च शिक्षण",
    other_occupation_placeholder: "कृपया तुमचा व्यवसाय सांगा...",
    income_field: "वार्षिक कौटुंबिक उत्पन्न (₹)",
    income_hint: "वार्षिक कौटुंबिक उत्पन्न",
    category_field: "सामाजिक श्रेणी",
    find_btn: "🎯 माझ्या योजना शोधा",
    results_found: "योजना सापडल्या!", no_results: "कोणतीही योजना जुळली नाही",
    results_sub: "तुमच्या प्रोफाइलनुसार पात्रता तपासली गेली.",
    ai_label: "🤖 AI शिफारस",
    view_detail: "पाहा →",
    recheck: "↺ पुन्हा तपासा",
    no_scheme_msg: "तुमच्या निकषांसाठी कोणतीही योजना सापडली नाही.",
    welcome: "स्वागत",
    member_since: "सदस्य झाल्यापासून",
    stats_schemes: "योजना सूचीबद्ध", stats_cat: "श्रेणी", stats_citizens: "नागरिक लाभार्थी", stats_avail: "उपलब्ध",
    select_gender: "लिंग निवडा", male: "पुरुष", female: "महिला", other_gender: "इतर",
    select_state: "राज्य निवडा",
    select_occ: "व्यवसाय निवडा", student: "विद्यार्थी", farmer: "शेतकरी",
    self_emp: "स्वयंरोजगार / व्यवसाय", govt_emp: "शासकीय कर्मचारी",
    pvt_emp: "खाजगी कर्मचारी", unemployed: "बेरोजगार", other_occ: "इतर (कृपया सांगा)",
    select_edu: "शिक्षण निवडा", below_10th: "10वी पेक्षा कमी / शाळेत जाणारे",
    none_baby: "लागू नाही (बालक/अर्भक)", edu_10th: "10वी पास", edu_12th: "12वी पास",
    graduation: "पदवी", post_grad: "पदव्युत्तर", diploma: "डिप्लोमा / ITI",
    select_cat: "श्रेणी निवडा", general: "सामान्य", obc: "OBC", sc: "SC", st: "ST",
    minority: "अल्पसंख्याक", ews: "EWS",
    income_exceeded: "⚠️ तुमच्या उत्पन्नानुसार तुम्ही काही योजनांसाठी पात्र नसाल.",
    footer_copy: "योजना पोर्टल — भारत सरकारच्या ओपन डेटावर आधारित",
    footer_sub: "भारतीय नागरिकांसाठी ❤️ सह बनवले · ही अधिकृत सरकारी वेबसाइट नाही",
    language_label: "🌐 भाषा",
    pm_section: "पंतप्रधानांचा संदेश",
    view_details: "तपशील पाहा",
  },
  bn: {
    appName: "যোজনা পোর্টাল", tagline: "সরকারি প্রকল্প অনুসন্ধানকারী",
    nav_home: "🏠 হোম", nav_schemes: "📋 প্রকল্প", nav_checker: "✅ যোগ্যতা",
    login_btn: "লগইন / সাইন আপ", logout: "লগআউট",
    hero_title1: "আপনার প্রকল্প খুঁজুন,", hero_title2: "আপনার অধিকার পান",
    hero_sub: "৫০০+ সরকারি প্রকল্প এক জায়গায়। যোগ্যতা যাচাই করুন এবং সরাসরি আবেদন করুন।",
    search_placeholder: "প্রকল্প খুঁজুন...", search_btn: "খুঁজুন",
    quick_actions: "দ্রুত কার্যক্রম", check_elig: "যোগ্যতা যাচাই", check_elig_desc: "আপনার প্রোফাইলের ভিত্তিতে প্রকল্প খুঁজুন",
    edu_schemes: "শিক্ষা প্রকল্প", edu_desc: "বৃত্তি ও শিক্ষা সহায়তা",
    farm_schemes: "কৃষক প্রকল্প", farm_desc: "কৃষি প্রকল্প ও ভর্তুকি",
    health_schemes: "স্বাস্থ্য প্রকল্প", health_desc: "চিকিৎসা সহায়তা ও বীমা",
    explore: "দেখুন →", all_schemes: "সব সরকারি প্রকল্প", all_schemes_sub: "কেন্দ্রীয় সরকারি প্রকল্পের সম্পূর্ণ ডেটাবেস।",
    schemes_found: "প্রকল্প পাওয়া গেছে", ministry: "মন্ত্রণালয়",
    benefit: "সুবিধার পরিমাণ", deadline_lbl: "শেষ তারিখ",
    req_docs: "📄 প্রয়োজনীয় নথি", eligibility_lbl: "✅ যোগ্যতা",
    apply_btn: "🚀 অফিসিয়াল ওয়েবসাইটে আবেদন করুন",
    all_genders: "সব লিঙ্গ", female_only: "শুধু মহিলা", male_only: "পুরুষ",
    age_lbl: "বয়স", income_lbl: "আয়",
    checker_title: "যোগ্যতা যাচাইকারী", checker_sub: "আপনার তথ্য পূরণ করুন।",
    login_required: "লগইন প্রয়োজন", login_required_sub: "যোগ্যতা যাচাই ব্যবহার করতে লগইন করুন।",
    login_to_continue: "🔑 লগইন / সাইন আপ",
    step1: "ব্যক্তিগত তথ্য", step2: "শিক্ষা ও কাজ", step3: "আয় ও বিভাগ", step4: "আপনার প্রকল্প",
    age_field: "আপনার বয়স *", gender_field: "লিঙ্গ *", state_field: "রাজ্য",
    next_btn: "পরবর্তী →", back_btn: "← পিছনে",
    occupation_field: "বর্তমান পেশা *", education_field: "সর্বোচ্চ শিক্ষা",
    other_occupation_placeholder: "আপনার পেশা বর্ণনা করুন...",
    income_field: "বার্ষিক পারিবারিক আয় (₹)", income_hint: "বার্ষিক পারিবারিক আয়",
    category_field: "সামাজিক বিভাগ", find_btn: "🎯 আমার প্রকল্প খুঁজুন",
    results_found: "প্রকল্প পাওয়া গেছে!", no_results: "কোনো প্রকল্প মেলেনি",
    results_sub: "আপনার প্রোফাইলের ভিত্তিতে যোগ্যতা যাচাই করা হয়েছে।",
    ai_label: "🤖 AI সুপারিশ", view_detail: "দেখুন →", recheck: "↺ আবার যাচাই করুন",
    no_scheme_msg: "আপনার মানদণ্ডের জন্য কোনো প্রকল্প পাওয়া যায়নি।",
    welcome: "স্বাগতম", member_since: "সদস্য হয়েছেন",
    stats_schemes: "প্রকল্প তালিকাভুক্ত", stats_cat: "বিভাগ", stats_citizens: "নাগরিক উপকৃত", stats_avail: "উপলব্ধ",
    select_gender: "লিঙ্গ নির্বাচন করুন", male: "পুরুষ", female: "মহিলা", other_gender: "অন্যান্য",
    select_state: "রাজ্য নির্বাচন করুন",
    select_occ: "পেশা নির্বাচন করুন", student: "শিক্ষার্থী", farmer: "কৃষক",
    self_emp: "স্ব-কর্মসংস্থান", govt_emp: "সরকারি কর্মচারী", pvt_emp: "বেসরকারি কর্মচারী",
    unemployed: "বেকার", other_occ: "অন্যান্য (বর্ণনা করুন)",
    select_edu: "শিক্ষা নির্বাচন করুন", below_10th: "দশম শ্রেণীর নিচে",
    none_baby: "প্রযোজ্য নয় (শিশু)", edu_10th: "দশম পাস", edu_12th: "দ্বাদশ পাস",
    graduation: "স্নাতক", post_grad: "স্নাতকোত্তর", diploma: "ডিপ্লোমা / আইটিআই",
    select_cat: "বিভাগ নির্বাচন করুন", general: "সাধারণ", obc: "OBC", sc: "SC", st: "ST",
    minority: "সংখ্যালঘু", ews: "EWS",
    income_exceeded: "⚠️ আপনার আয়ের ভিত্তিতে আপনি কিছু প্রকল্পের জন্য যোগ্য নাও হতে পারেন।",
    footer_copy: "যোজনা পোর্টাল — ভারত সরকারের ওপেন ডেটা দ্বারা চালিত",
    footer_sub: "ভারতীয় নাগরিকদের জন্য ❤️ দিয়ে তৈরি",
    language_label: "🌐 ভাষা", pm_section: "প্রধানমন্ত্রীর বার্তা", view_details: "বিস্তারিত দেখুন",
  },
  ta: {
    appName: "யோஜனா போர்டல்", tagline: "அரசு திட்ட தேடல்",
    nav_home: "🏠 முகப்பு", nav_schemes: "📋 திட்டங்கள்", nav_checker: "✅ தகுதி",
    login_btn: "உள்நுழை / பதிவு செய்", logout: "வெளியேறு",
    hero_title1: "உங்கள் திட்டத்தை கண்டறியுங்கள்,", hero_title2: "உங்கள் உரிமையை பெறுங்கள்",
    hero_sub: "500+ அரசு திட்டங்கள் ஒரே இடத்தில். தகுதியை சரிபாருங்கள், ஆவணங்களை அறியுங்கள்.",
    search_placeholder: "திட்டங்களை தேடுங்கள்...", search_btn: "தேடு",
    quick_actions: "விரைவு செயல்கள்", check_elig: "தகுதியை சரிபார்", check_elig_desc: "உங்கள் சுயவிவரத்தின் படி திட்டங்கள் கண்டறியுங்கள்",
    edu_schemes: "கல்வி திட்டங்கள்", edu_desc: "உதவித்தொகை மற்றும் கல்வி ஆதரவு",
    farm_schemes: "விவசாயி திட்டங்கள்", farm_desc: "விவசாய திட்டங்கள் மற்றும் மானியங்கள்",
    health_schemes: "சுகாதார திட்டங்கள்", health_desc: "மருத்துவ ஆதரவு மற்றும் காப்பீடு",
    explore: "பார்க்க →", all_schemes: "அனைத்து அரசு திட்டங்கள்", all_schemes_sub: "மத்திய அரசின் அனைத்து திட்டங்களும்.",
    schemes_found: "திட்டங்கள் கிடைத்தன", ministry: "அமைச்சகம்",
    benefit: "நலன் தொகை", deadline_lbl: "கடைசி தேதி",
    req_docs: "📄 தேவையான ஆவணங்கள்", eligibility_lbl: "✅ தகுதி",
    apply_btn: "🚀 அதிகாரப்பூர்வ இணையதளத்தில் விண்ணப்பிக்கவும்",
    all_genders: "அனைத்து பாலினமும்", female_only: "பெண்கள் மட்டும்", male_only: "ஆண்",
    age_lbl: "வயது", income_lbl: "வருமானம்",
    checker_title: "தகுதி சரிபார்ப்பாளர்", checker_sub: "உங்கள் விவரங்களை நிரப்புங்கள்.",
    login_required: "உள்நுழைவு தேவை", login_required_sub: "தகுதி சரிபார்க்க உள்நுழையுங்கள்.",
    login_to_continue: "🔑 உள்நுழை / பதிவு செய்",
    step1: "தனிப்பட்ட தகவல்", step2: "கல்வி மற்றும் தொழில்", step3: "வருமானம் மற்றும் வகை", step4: "உங்கள் திட்டங்கள்",
    age_field: "உங்கள் வயது *", gender_field: "பாலினம் *", state_field: "மாநிலம்",
    next_btn: "அடுத்து →", back_btn: "← பின்னால்",
    occupation_field: "தற்போதைய தொழில் *", education_field: "உயர்ந்த கல்வி",
    other_occupation_placeholder: "உங்கள் தொழிலை விவரிக்கவும்...",
    income_field: "ஆண்டு குடும்ப வருமானம் (₹)", income_hint: "ஆண்டு குடும்ப வருமானம்",
    category_field: "சமூக வகை", find_btn: "🎯 என் திட்டங்களை கண்டறி",
    results_found: "திட்டங்கள் கண்டறியப்பட்டன!", no_results: "எந்த திட்டமும் பொருந்தவில்லை",
    results_sub: "உங்கள் சுயவிவரத்தின் படி தகுதி சரிபார்க்கப்பட்டது.",
    ai_label: "🤖 AI பரிந்துரை", view_detail: "பார்க்க →", recheck: "↺ மீண்டும் சரிபார்",
    no_scheme_msg: "உங்கள் தகவலுக்கு திட்டங்கள் இல்லை.",
    welcome: "வரவேற்கிறோம்", member_since: "உறுப்பினர் ஆனது",
    stats_schemes: "திட்டங்கள் பட்டியல்", stats_cat: "வகைகள்", stats_citizens: "குடிமக்கள் பயனடைந்தனர்", stats_avail: "கிடைக்கிறது",
    select_gender: "பாலினம் தேர்வு", male: "ஆண்", female: "பெண்", other_gender: "மற்றவை",
    select_state: "மாநிலம் தேர்வு",
    select_occ: "தொழில் தேர்வு", student: "மாணவர்", farmer: "விவசாயி",
    self_emp: "சுய தொழில்", govt_emp: "அரசு ஊழியர்", pvt_emp: "தனியார் ஊழியர்",
    unemployed: "வேலையில்லாதவர்", other_occ: "மற்றவை (விவரிக்கவும்)",
    select_edu: "கல்வி தேர்வு", below_10th: "10ஆம் வகுப்புக்கு கீழ்",
    none_baby: "பொருந்தாது (குழந்தை)", edu_10th: "10ஆம் வகுப்பு தேர்ச்சி", edu_12th: "12ஆம் வகுப்பு தேர்ச்சி",
    graduation: "பட்டம்", post_grad: "முதுகலை", diploma: "டிப்ளோமா / ITI",
    select_cat: "வகை தேர்வு", general: "பொது", obc: "OBC", sc: "SC", st: "ST",
    minority: "சிறுபான்மை", ews: "EWS",
    income_exceeded: "⚠️ உங்கள் வருமானத்தின் படி சில திட்டங்களுக்கு தகுதி இல்லாமல் போகலாம்.",
    footer_copy: "யோஜனா போர்டல் — இந்திய அரசின் திறந்த தரவு மூலம்",
    footer_sub: "இந்திய குடிமக்களுக்காக ❤️ உடன் உருவாக்கப்பட்டது",
    language_label: "🌐 மொழி", pm_section: "பிரதமரின் செய்தி", view_details: "விவரங்கள் பார்க்க",
  },
  te: {
    appName: "యోజన పోర్టల్", tagline: "ప్రభుత్వ పథకం సెర్చ్",
    nav_home: "🏠 హోమ్", nav_schemes: "📋 పథకాలు", nav_checker: "✅ అర్హత",
    login_btn: "లాగిన్ / సైన్ అప్", logout: "లాగ్అవుట్",
    hero_title1: "మీ పథకాన్ని కనుగొనండి,", hero_title2: "మీ హక్కు పొందండి",
    hero_sub: "500+ ప్రభుత్వ పథకాలు ఒక చోట. అర్హత తనిఖీ చేయండి మరియు నేరుగా దరఖాస్తు చేయండి.",
    search_placeholder: "పథకాలు వెతకండి...", search_btn: "వెతకు",
    quick_actions: "త్వరిత చర్యలు", check_elig: "అర్హత తనిఖీ", check_elig_desc: "మీ ప్రొఫైల్ ఆధారంగా పథకాలు కనుగొనండి",
    edu_schemes: "విద్య పథకాలు", edu_desc: "స్కాలర్‌షిప్‌లు మరియు విద్యా సహాయం",
    farm_schemes: "రైతు పథకాలు", farm_desc: "వ్యవసాయ పథకాలు మరియు సబ్సిడీలు",
    health_schemes: "ఆరోగ్య పథకాలు", health_desc: "వైద్య సహాయం మరియు బీమా",
    explore: "చూడు →", all_schemes: "అన్ని ప్రభుత్వ పథకాలు", all_schemes_sub: "కేంద్ర ప్రభుత్వ పథకాల పూర్తి డేటాబేస్.",
    schemes_found: "పథకాలు దొరికాయి", ministry: "మంత్రిత్వ శాఖ",
    benefit: "లాభం మొత్తం", deadline_lbl: "చివరి తేదీ",
    req_docs: "📄 అవసరమైన పత్రాలు", eligibility_lbl: "✅ అర్హత",
    apply_btn: "🚀 అధికారిక వెబ్‌సైట్‌లో దరఖాస్తు చేయండి",
    all_genders: "అన్ని లింగాలు", female_only: "స్త్రీలు మాత్రమే", male_only: "పురుషుడు",
    age_lbl: "వయస్సు", income_lbl: "ఆదాయం",
    checker_title: "అర్హత తనిఖీదారు", checker_sub: "మీ వివరాలు నమోదు చేయండి.",
    login_required: "లాగిన్ అవసరం", login_required_sub: "అర్హత తనిఖీ ఉపయోగించడానికి లాగిన్ చేయండి.",
    login_to_continue: "🔑 లాగిన్ / సైన్ అప్",
    step1: "వ్యక్తిగత సమాచారం", step2: "విద్య మరియు పని", step3: "ఆదాయం మరియు వర్గం", step4: "మీ పథకాలు",
    age_field: "మీ వయస్సు *", gender_field: "లింగం *", state_field: "రాష్ట్రం",
    next_btn: "తదుపరి →", back_btn: "← వెనుకకు",
    occupation_field: "ప్రస్తుత వృత్తి *", education_field: "అత్యున్నత విద్యార్హత",
    other_occupation_placeholder: "మీ వృత్తిని వివరించండి...",
    income_field: "వార్షిక కుటుంబ ఆదాయం (₹)", income_hint: "వార్షిక కుటుంబ ఆదాయం",
    category_field: "సామాజిక వర్గం", find_btn: "🎯 నా పథకాలు కనుగొనండి",
    results_found: "పథకాలు కనుగొనబడ్డాయి!", no_results: "ఏ పథకం సరిపోలలేదు",
    results_sub: "మీ ప్రొఫైల్ ఆధారంగా అర్హత తనిఖీ చేయబడింది.",
    ai_label: "🤖 AI సిఫారసు", view_detail: "చూడు →", recheck: "↺ మళ్ళీ తనిఖీ చేయండి",
    no_scheme_msg: "మీ ప్రమాణాలకు పథకాలు లేవు.",
    welcome: "స్వాగతం", member_since: "సభ్యుడైన తేదీ",
    stats_schemes: "పథకాలు జాబితా చేయబడ్డాయి", stats_cat: "వర్గాలు", stats_citizens: "పౌరులకు ప్రయోజనం", stats_avail: "అందుబాటులో",
    select_gender: "లింగం ఎంచుకోండి", male: "పురుషుడు", female: "స్త్రీ", other_gender: "ఇతర",
    select_state: "రాష్ట్రం ఎంచుకోండి",
    select_occ: "వృత్తి ఎంచుకోండి", student: "విద్యార్థి", farmer: "రైతు",
    self_emp: "స్వయం ఉపాధి", govt_emp: "ప్రభుత్వ ఉద్యోగి", pvt_emp: "ప్రైవేట్ ఉద్యోగి",
    unemployed: "నిరుద్యోగి", other_occ: "ఇతర (వివరించండి)",
    select_edu: "విద్య ఎంచుకోండి", below_10th: "10వ తరగతి కంటే తక్కువ",
    none_baby: "వర్తించదు (శిశువు)", edu_10th: "10వ తరగతి పాస్", edu_12th: "12వ తరగతి పాస్",
    graduation: "పట్టభద్రుడు", post_grad: "స్నాతకోత్తర", diploma: "డిప్లొమా / ITI",
    select_cat: "వర్గం ఎంచుకోండి", general: "సాధారణ", obc: "OBC", sc: "SC", st: "ST",
    minority: "మైనారిటీ", ews: "EWS",
    income_exceeded: "⚠️ మీ ఆదాయం ఆధారంగా మీరు కొన్ని పథకాలకు అర్హులు కాకపోవచ్చు.",
    footer_copy: "యోజన పోర్టల్ — భారత ప్రభుత్వ ఓపెన్ డేటా ద్వారా",
    footer_sub: "భారతీయ పౌరుల కోసం ❤️తో తయారు చేయబడింది",
    language_label: "🌐 భాష", pm_section: "ప్రధానమంత్రి సందేశం", view_details: "వివరాలు చూడు",
  },
  gu: {
    appName: "યોજના પોર્ટલ", tagline: "સરકારી યોજના શોધક",
    nav_home: "🏠 હોમ", nav_schemes: "📋 યોજનાઓ", nav_checker: "✅ પાત્રતા",
    login_btn: "લૉગિન / સાઇન અપ", logout: "લૉગઆઉટ",
    hero_title1: "તમારી યોજના શોધો,", hero_title2: "તમારો હક મેળવો",
    hero_sub: "500+ સરકારી યોજનાઓ એક જ જગ્યાએ. પાત્રતા ચકાસો અને સીધી અરજી કરો.",
    search_placeholder: "યોજનાઓ શોધો...", search_btn: "શોધો",
    quick_actions: "ઝડપી ક્રિયાઓ", check_elig: "પાત્રતા ચકાસો", check_elig_desc: "તમારી પ્રોફાઇલ આધારે યોજનાઓ શોધો",
    edu_schemes: "શિક્ષણ યોજનાઓ", edu_desc: "શિષ્યવૃત્તિ અને શૈક્ષણિક સહાય",
    farm_schemes: "ખેડૂત યોજનાઓ", farm_desc: "કૃષિ યોજनाઓ અને સબ્સિડી",
    health_schemes: "આરોગ્ય યોજनाઓ", health_desc: "તબીબી સહાય અને વીમો",
    explore: "જુઓ →", all_schemes: "તમામ સરકારી યોજnaઓ", all_schemes_sub: "કેન્દ્ર સરکارni तمाम yojnaઓ.",
    schemes_found: "yojnaઓ મળી", ministry: "মন্ত্রालय",
    benefit: "લાભ રકم", deadline_lbl: "છेल्ली তারিখ",
    req_docs: "📄 জরুরি দस्तावেज", eligibility_lbl: "✅ পাত্রতা",
    apply_btn: "🚀 અधिকৃত ওয়েবসাইটে অর্জী করો",
    all_genders: "तمाम जাতি", female_only: "ফেমेल", male_only: "পুরুষ",
    age_lbl: "ঊমর", income_lbl: "আয়",
    checker_title: "পাত্রতা চেकর", checker_sub: "তমारী মাহিতী ভरो.",
    login_required: "লগিন জরূরি", login_required_sub: "পাত্রতা চেক করতে লগিন করো.",
    login_to_continue: "🔑 লगिन / সাइন আপ",
    step1: "ব্যक्তिগত মাহিতী", step2: "শিক্ষণ ও কাম", step3: "আয় ও জাতি", step4: "তमारी যোজनা",
    age_field: "তমারी ঊмर *", gender_field: "জাতি *", state_field: "রাজ্য",
    next_btn: "আগে →", back_btn: "← পাछে",
    occupation_field: "বর্তমান ব্যবসায় *", education_field: "ঊচ্চতম শিক্ষণ",
    other_occupation_placeholder: "তমारो ব্যবসায় বतাও...",
    income_field: "বার্षিক কুটুम্ব আয় (₹)", income_hint: "বার্षিক পারিবারিক আয়",
    category_field: "সামाজिক জাতি", find_btn: "🎯 মারি যোজনা শোধো",
    results_found: "যোজनাઓ মળী!", no_results: "কোई যোজنا ম‍ेళী नহीं",
    results_sub: "তমারী প্রোফাইল আधारে পাত্রতা ছেক করী.",
    ai_label: "🤖 AI সুझাव", view_detail: "জুও →", recheck: "↺ ফরী ছেক করো",
    no_scheme_msg: "তমारा মापदণ্ড মাটে কোই যোজna न‍হীং.",
    welcome: "স্বাগত", member_since: "সদস্য বন্যা থী",
    stats_schemes: "যোজnাઓ যادी", stats_cat: "শ্রেণী", stats_citizens: "নাগরিক লাভান্বিত", stats_avail: "উপলব্ধ",
    select_gender: "জाति সিলেক্ট करো", male: "পুরুষ", female: "স্ত্রী", other_gender: "অন্য",
    select_state: "রাজ্য সিলেক্ট করো",
    select_occ: "ব্যবসায় সিলেক্ট করো", student: "বিদ্যার্থী", farmer: "খেডূত",
    self_emp: "স্বরোজগার", govt_emp: "সরকারী কर्मচারী", pvt_emp: "ব্যক্তিগত কর্মচারী",
    unemployed: "বেরোজগার", other_occ: "অন্য (বতাও)",
    select_edu: "শিক্ষণ সিলেক্ট করো", below_10th: "দহেম থী ওছী",
    none_baby: "লাগু নহি (শিশু)", edu_10th: "দশম পাস", edu_12th: "বারহ পাস",
    graduation: "গ্রाজুয়েশন", post_grad: "পোস্ট গ্র্যাজুয়েশন", diploma: "ডিप्লোমা / ITI",
    select_cat: "জाতি সিলেক্ট করো", general: "সামান্য", obc: "OBC", sc: "SC", st: "ST",
    minority: "লঘুমতি", ews: "EWS",
    income_exceeded: "⚠️ তমারী আয় আধারে তমे কেটলীক যোজnাઓ মাটে পাত্র ন হয়.",
    footer_copy: "যোজনা পোর্টল — ভারত সরকারना ওপেন ডেটা আধারিত",
    footer_sub: "ভারতীয় নাগরিকো মাটে ❤️ সাথে বনাব্যুং",
    language_label: "🌐 ভाষা", pm_section: "PM নো সন্দেশ", view_details: "বিगত জুও",
  },
  kn: {
    appName: "ಯೋಜನಾ ಪೋರ್ಟಲ್", tagline: "ಸರ್ಕಾರಿ ಯೋಜನೆ ಹುಡುಕಾಟ",
    nav_home: "🏠 ಮುಖಪುಟ", nav_schemes: "📋 ಯೋಜನೆಗಳು", nav_checker: "✅ ಅರ್ಹತೆ",
    login_btn: "ಲಾಗಿನ್ / ಸೈನ್ ಅಪ್", logout: "ಲಾಗ್ಔಟ್",
    hero_title1: "ನಿಮ್ಮ ಯೋಜನೆ ಹುಡುಕಿ,", hero_title2: "ನಿಮ್ಮ ಹಕ್ಕು ಪಡೆಯಿರಿ",
    hero_sub: "500+ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ. ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನೇರವಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    search_placeholder: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...", search_btn: "ಹುಡುಕಿ",
    quick_actions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು", check_elig: "ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ", check_elig_desc: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಆಧಾರದಲ್ಲಿ ಯೋಜನೆಗಳು",
    edu_schemes: "ಶಿಕ್ಷಣ ಯೋಜನೆಗಳು", edu_desc: "ವಿದ್ಯಾರ್ಥಿವೇತನ ಮತ್ತು ಶಿಕ್ಷಣ ಬೆಂಬಲ",
    farm_schemes: "ರೈತ ಯೋಜನೆಗಳು", farm_desc: "ಕೃಷಿ ಯೋಜನೆಗಳು ಮತ್ತು ಸಬ್ಸಿಡಿ",
    health_schemes: "ಆರೋಗ್ಯ ಯೋಜನೆಗಳು", health_desc: "ವೈದ್ಯಕೀಯ ಬೆಂಬಲ ಮತ್ತು ವಿಮೆ",
    explore: "ನೋಡಿ →", all_schemes: "ಎಲ್ಲಾ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು", all_schemes_sub: "ಕೇಂದ್ರ ಸರ್ಕಾರದ ಎಲ್ಲಾ ಯೋಜನೆಗಳ ಡೇಟಾಬೇಸ್.",
    schemes_found: "ಯೋಜನೆಗಳು ಸಿಕ್ಕಿವೆ", ministry: "ಸಚಿವಾಲಯ",
    benefit: "ಲಾಭದ ಮೊತ್ತ", deadline_lbl: "ಕೊನೆ ದಿನಾಂಕ",
    req_docs: "📄 ಅಗತ್ಯ ದಾಖಲೆಗಳು", eligibility_lbl: "✅ ಅರ್ಹತೆ",
    apply_btn: "🚀 ಅಧಿಕೃತ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    all_genders: "ಎಲ್ಲಾ ಲಿಂಗಗಳು", female_only: "ಮಹಿಳೆಯರು ಮಾತ್ರ", male_only: "ಪುರುಷ",
    age_lbl: "ವಯಸ್ಸು", income_lbl: "ಆದಾಯ",
    checker_title: "ಅರ್ಹತೆ ಪರಿಶೀಲಕ", checker_sub: "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ತುಂಬಿಸಿ.",
    login_required: "ಲಾಗಿನ್ ಅಗತ್ಯ", login_required_sub: "ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ.",
    login_to_continue: "🔑 ಲಾಗಿನ್ / ಸೈನ್ ಅಪ್",
    step1: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ", step2: "ಶಿಕ್ಷಣ ಮತ್ತು ಕೆಲಸ", step3: "ಆದಾಯ ಮತ್ತು ವರ್ಗ", step4: "ನಿಮ್ಮ ಯೋಜನೆಗಳು",
    age_field: "ನಿಮ್ಮ ವಯಸ್ಸು *", gender_field: "ಲಿಂಗ *", state_field: "ರಾಜ್ಯ",
    next_btn: "ಮುಂದೆ →", back_btn: "← ಹಿಂದೆ",
    occupation_field: "ಪ್ರಸ್ತುತ ಉದ್ಯೋಗ *", education_field: "ಅತ್ಯುನ್ನತ ಶಿಕ್ಷಣ",
    other_occupation_placeholder: "ನಿಮ್ಮ ಉದ್ಯೋಗವನ್ನು ವಿವರಿಸಿ...",
    income_field: "ವಾರ್ಷಿಕ ಕುಟುಂಬ ಆದಾಯ (₹)", income_hint: "ವಾರ್ಷಿಕ ಕುಟುಂಬ ಆದಾಯ",
    category_field: "ಸಾಮಾಜಿಕ ವರ್ಗ", find_btn: "🎯 ನನ್ನ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    results_found: "ಯೋಜನೆಗಳು ಸಿಕ್ಕಿದೆ!", no_results: "ಯಾವ ಯೋಜನೆಯೂ ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ",
    results_sub: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಆಧಾರದಲ್ಲಿ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.",
    ai_label: "🤖 AI ಶಿಫಾರಸು", view_detail: "ನೋಡಿ →", recheck: "↺ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ",
    no_scheme_msg: "ನಿಮ್ಮ ಮಾನದಂಡಗಳಿಗೆ ಯೋಜನೆಗಳಿಲ್ಲ.",
    welcome: "ಸ್ವಾಗತ", member_since: "ಸದಸ್ಯರಾದ ದಿನಾಂಕ",
    stats_schemes: "ಯೋಜನೆಗಳು ಪಟ್ಟಿ ಮಾಡಲಾಗಿದೆ", stats_cat: "ವರ್ಗಗಳು", stats_citizens: "ನಾಗರಿಕರಿಗೆ ಪ್ರಯೋಜನ", stats_avail: "ಲಭ್ಯ",
    select_gender: "ಲಿಂಗ ಆಯ್ಕೆ ಮಾಡಿ", male: "ಪುರುಷ", female: "ಮಹಿಳೆ", other_gender: "ಇತರೆ",
    select_state: "ರಾಜ್ಯ ಆಯ್ಕೆ ಮಾಡಿ",
    select_occ: "ಉದ್ಯೋಗ ಆಯ್ಕೆ ಮಾಡಿ", student: "ವಿದ್ಯಾರ್ಥಿ", farmer: "ರೈತ",
    self_emp: "ಸ್ವ-ಉದ್ಯೋಗ", govt_emp: "ಸರ್ಕಾರಿ ಉದ್ಯೋಗಿ", pvt_emp: "ಖಾಸಗಿ ಉದ್ಯೋಗಿ",
    unemployed: "ನಿರುದ್ಯೋಗಿ", other_occ: "ಇತರೆ (ವಿವರಿಸಿ)",
    select_edu: "ಶಿಕ್ಷಣ ಆಯ್ಕೆ ಮಾಡಿ", below_10th: "10ನೇ ತರಗತಿಗಿಂತ ಕೆಳಗೆ",
    none_baby: "ಅನ್ವಯಿಸುವುದಿಲ್ಲ (ಶಿಶು)", edu_10th: "10ನೇ ತರಗತಿ ಪಾಸ್", edu_12th: "12ನೇ ತರಗತಿ ಪಾಸ್",
    graduation: "ಪದವಿ", post_grad: "ಸ್ನಾತಕೋತ್ತರ", diploma: "ಡಿಪ್ಲೊಮಾ / ITI",
    select_cat: "ವರ್ಗ ಆಯ್ಕೆ ಮಾಡಿ", general: "ಸಾಮಾನ್ಯ", obc: "OBC", sc: "SC", st: "ST",
    minority: "ಅಲ್ಪಸಂಖ್ಯಾತ", ews: "EWS",
    income_exceeded: "⚠️ ನಿಮ್ಮ ಆದಾಯದ ಆಧಾರದಲ್ಲಿ ಕೆಲವು ಯೋಜನೆಗಳಿಗೆ ಅರ್ಹರಾಗಿರದಿರಬಹುದು.",
    footer_copy: "ಯೋಜನಾ ಪೋರ್ಟಲ್ — ಭಾರತ ಸರ್ಕಾರದ ಓಪನ್ ಡೇಟಾ ಮೂಲಕ",
    footer_sub: "ಭಾರತೀಯ ನಾಗರಿಕರಿಗಾಗಿ ❤️ ನೊಂದಿಗೆ ತಯಾರಿಸಲಾಗಿದೆ",
    language_label: "🌐 ಭಾಷೆ", pm_section: "ಪ್ರಧಾನಮಂತ್ರಿ ಸಂದೇಶ", view_details: "ವಿವರಗಳನ್ನು ನೋಡಿ",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = T[lang] || T.en;
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() { return useContext(LangContext); }
